MODEL: 'gpt-3.5-turbo-0301'
# PROMPT: "Write a long, fun and creative content for a README.md file. Inter-relate the contents of the repository and understand what the {0} repository does. Write the content in raw markdown format."
PROMPT: "You are a expert in converting the context into jinja templates. now with the context, fill up the below jinja template: \n"
