AI_MODE: 'code'
MODEL: 'gpt-3.5-turbo-0301'
PROMPT: "Write a long, fun and creative content for a README.md file. Inter-relate the contents of the repository and understand what the {0} repository does. Write the content in raw markdown format."